### PR TITLE
Remove unused code in CarbonRow

### PR DESCRIPTION
**Pull request by jarray888**
Clean up CarbonRow

### CODE REVIEW

**Comment by jarray888** [comment]
test this please

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Failed, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/47/

**Comment by jarray888** [comment]
ok to test

**Comment by CarbonDataQA** [comment]
Build Success, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/48/

**Pull request closed without merging**
