### PR TITLE
[CARBONDATA-177] Greater than and Less than filter returning wrong result

### PR DESCRIPTION
**Pull request by mohammadshahidkhan**

### CODE REVIEW

**Comment by kumarvishal09** [comment]
LGTM

**Comment by chenliang613** [comment]
Not passed CI test , please check : http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/12/

**Comment by Vimal-Das** [comment]
@mohammadshahidkhan Please provide description in the PR describing the cases when Greater Than and Less Than are returning wrong result.

**Comment by mohammadshahidkhan** [comment]
@Vimal-Das Please find the below scenario
DDL:
"CREATE TABLE IF NOT EXISTS carbonTable(date Timestamp, country String, salary Int) STORED " +
"BY " +
"'carbondata'
Data:
2015-7-23 12:07:28,china,15000
2018-7-24 12:07:28,china,15001
2017-7-25 12:07:28,china,15002
Load command:
"LOAD DATA LOCAL INPATH '" + csvFilePath + "' into table carbonTable OPTIONS " +
"('FILEHEADER'='date,country,salary')"
Scenario:
1. when the filter value does not match any of the value of the table.
select * from carbonTable where date > '2017-7-25 12:07:29'
throwing ArrayIndexOutOfBoundException

2.  when the filter value matches with the values in table the result is not matching with hive
select * from carbonTable where date > '2017-7-25 12:07:28'
!== Correct Answer - 2 ==              == Spark Answer - 1 ==
 [2015-07-23 12:07:28.0,china,15000]   [2015-07-23 12:07:28.0,china,15000]
![2017-07-25 12:07:28.0,china,15002] 

select * from carbonTable where date > '2017-7-25 12:07:28'

!== Correct Answer - 3 ==              == Spark Answer - 2 ==
 [2015-07-23 12:07:28.0,china,15000]   [2015-07-23 12:07:28.0,china,15000]
 [2017-07-25 12:07:28.0,china,15002]   [2017-07-25 12:07:28.0,china,15002]
![2018-07-24 12:07:28.0,china,15001]

**Comment by ravipesala** [comment]
@mohammadshahidkhan I guess there is no issue in carbon. But in the testcase the filter of hive should be cast to timestamp. Like as below. Please correct all the testcases in that suite and we can merge it.

```
test("select * from carbonTable where date < cast('2018-7-24 12:07:28' as timestamp)") {
    checkAnswer(
      sql("select * from carbonTable where date < cast('2018-7-24 12:07:28' as timestamp)"),
      sql("select * from hiveTable where date < cast('2018-7-24 12:07:28' as timestamp)")
    )
  }
```

**Comment by mohammadshahidkhan** [comment]
PR build successful
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/50/

**Comment by ravipesala** [comment]
LGTM

**Comment by Vimal-Das** [comment]
LGTM

**Pull request closed without merging**
