### PR TITLE
[CARBONDATA-943] Added check to display error message in catch block

### PR DESCRIPTION
**Pull request by ManoharVanam**
problem : Failing Mathematical functional in spark 2.1 is not displaying proper error message
Solution : Added check to display error message in catch block

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1668/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1673/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1744/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
