### PR TITLE
[CARBONDATA-762] Change schemaName to databaseName, cubeName to table…

### PR DESCRIPTION
**Pull request by lionelcao**
Change schemaName to databaseName, cubeName to tableName

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1146/

**Comment by chenliang613** [comment]
@lionelcao  please push a null commit to trigger the travis CI again,  CI should be ok.
verified in my machine ,it is ok.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1167/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
