### PR TITLE
[CARBONDATA-635]Insert query fails when functions are used in select query

### PR DESCRIPTION
**Pull request by ravipesala**
This PR fixes the insert query when functions are used in select query.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/672/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/673/

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/674/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
