### PR TITLE
[CARBONDATA-697] Jira single_pass is not used while doing data load

### PR DESCRIPTION
**Pull request by BJangir**
CARBONDATA-697 
Issue :- single_pass is not used while doing data load
Solution :- added the Single pass in carbonLoadModel which was missing for Spark2.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/897/

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/898/

**Comment by BJangir** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/902/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
