### PR TITLE
[CARBONDATA-413] Unit test case for expression.conditional package

### PR DESCRIPTION
**Pull request by anuragknoldus**
This PR contains complete unit test case for expression.conditional package.

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
ok to test

**Comment by ravipesala** [comment]
@anuragknoldus Please rename title from [Carbondata-413]  to [CARBONDATA-413]

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/115/

**Comment by anuragknoldus** [comment]
@ravipesala , I have renamed title.

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
