### PR TITLE
[CARBONDATA-102]Reduce the size of the CarbonData jar file.

### PR DESCRIPTION
**Pull request by ravipesala**
Following modifications done with this PR.
1. Refactored and cleaned POM to remove unnecessary dependency jar files.
2. Default CarbonData assembly jar does not include Spark, Scala and Hadoop dependencies. Example:
``` 
mvn clean -DskipTests package
```
3. User can provide profile `include-all` to include all dependencies. Example:
```
mvn clean -DskipTests -Pinclude-all package
```

Default size of CarbonData jar is 19MB
With including all dependencies, CarbonData jar size is 207MB

### CODE REVIEW

**Comment by chenliang613** [comment]
@QiangCai  please review it.

**Comment by QiangCai** [comment]
Verified, LGTM

**Comment by chenliang613** [comment]
@ravipesala  please update Building CarbonData documents accordingly.

**Comment by ravipesala** [comment]
@chenliang613 Updated documents, please review.

**Pull request closed without merging**
