### PR TITLE
[CARBONDATA-396] Implement test cases for datastorage package

### PR DESCRIPTION
**Pull request by harmeetsingh0013**
Write unit test cases for org.apache.carbondata.core.datastorage.store.columnar.BlockIndexerStorageForInt.java and org.apache.carbondata.core.datastorage.store.columnar.UnBlockIndexer.java

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by harmeetsingh0013** [comment]
yes @ravipesala , Is there any problem?

**Comment by ravipesala** [comment]
retest this please

**Comment by ravipesala** [comment]
@harmeetsingh0013  Please correct the PR title correctly.
It supposed to be [CARBONDATA-396], please correct for all your PRs

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/79/

**Comment by ravipesala** [comment]
LGTM

**Comment by ravipesala** [comment]
@harmeetsingh0013 It seems I could not rebase it because of conflicts in some of your commit.
Please squash all commits to 1 commit.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/118/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/144/

**Comment by jackylk** [comment]
retest this please

**Comment by harmeetsingh0013** [comment]
Hi @jackylk , at my end, the build create successfully. I am not sure, what is the problem CI, because according to dependencies, the problem with downloading dependencies.

**Pull request closed without merging**
