### PR TITLE
[CARBONDATA-450] added test cases for core.reader module

### PR DESCRIPTION
**Pull request by anubhav100**

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
@anubhav100 Please rebase it

**Comment by anubhav100** [comment]
@ravipesala rebased

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/112/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
