### PR TITLE
[CARBONDATA-578] Change case for default file format as V2 if property is not given

### PR DESCRIPTION
**Pull request by phalodi**
- Change case for default file format as V2 if property is not given
- Run all test cases manually
- Create build successfully

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/478/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
