### PR TITLE
[CARBONDATA-494] Added unit test cases for scan.filter.executer package

### PR DESCRIPTION
**Pull request by abhisheknoldus**

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
ok to test

**Comment by CarbonDataQA** [comment]
Build Success, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/33/

**Comment by ravipesala** [comment]
@abhisheknoldus Please don't add any binary files like include.carbondata

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/146/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/181/

**Comment by abhisheknoldus** [comment]
@ravipesala I have done the changes in test cases. Please check.

**Pull request closed without merging**
