### PR TITLE
[CARBONDATA-856] Alter Table - TABLE RENAME feature documentation

### PR DESCRIPTION
**Pull request by srigopalmohanty**
The documentation for Table rename as part of the alter table feature.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1496/

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
