### PR TITLE
[CARBONDATA-681] CSVReader related code improvement

### PR DESCRIPTION
**Pull request by JihongMA**
refactoring csv reader support during data loading, as well as replacing relevant classes out of Carbon Hadoop component into data loading component (processing).

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/754/

**Comment by jackylk** [comment]
@JihongMA Thanks for working on this, can you explain more about this PR, why CSVReader is moved to processing module?

**Comment by JihongMA** [comment]
CSVReader is only for data loading, processing module is more appropriate component to hold it. to me, Carbon Hadoop component is primarily for Carbon's input/output format for hadoop integration.

**Comment by jackylk** [comment]
ok, goods fine to me. please rebase the code

**Comment by jackylk** [comment]
@QiangCai please check the added data.csv in this PR, I remember there is a common data.csv for all test cases.

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/794/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/795/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/796/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/797/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
