### PR TITLE
[CARBONDATA-748] put if clause out of the for clause in method setFilterdIndexToBitSet

### PR DESCRIPTION
**Pull request by mayunSaicmotor**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[CARBONDATA-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).
 - [ ] Testing done
 
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - What manual testing you have done?
        - Any additional information to help reviewers in testing this change.
         
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
                 
---

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by chenliang613** [comment]
@mayunSaicmotor  please squash into one commit.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1089/

**Comment by mayunSaicmotor** [comment]
@Chen, Liang

Below is the step to change commit’s author information in git. Just for reference.
I have run in my fork repository  and raise PR. Please help to confirm. thanks very much.



1. find the previous  commit id of the needing amend commit，look as below
872945f is committed by me and need to change the author email id
6713ffa is the previous commit id



2.  run the below commit
git rebase -i -p 6713ffa

change the  pick to  edit before 872945f and type “wq” to exit



3. run the  below command to amend author information
	git commit --amend --author="mayun <simafengyun1984@163.com>" --no-edit
	git rebase -continue

4. run the below command to raise change to remote
	git push --force --tags origin 'refs/heads/*' -u

**Pull request closed without merging**
