### PR TITLE
[CARBONDATA-579] coverity and fortify fixes

### PR DESCRIPTION
**Pull request by sraghunandan**
fixed coverity and fortify issues in carbondata-core

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
ok to test

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/393/

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
