### PR TITLE
[CARBONDATA-743] Remove redundant CarbonFilters file

### PR DESCRIPTION
**Pull request by lionelcao**
Remove redundant CarbonFilters file in spark2 and keep the one in spark common

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1024/

**Comment by ravipesala** [comment]
@lionelcao Thank you for working on this,
But there are some differences in files from `CarbonFilters` of spark-common package and spark2 package. That is why I mentioned in jira to follow these steps,
1.Delete the CarbonFilters scala file from spark-common package
2. Move the CarbonFilters scala from spark2 package to spark-common package.

**Comment by lionelcao** [comment]
Hi @ravipesala , I compared those two files before commit and I think the difference has no impact to the functionality. Any ideas?

**Comment by ravipesala** [comment]
There is a difference in method `selectFilters` it takes one extra boolean in deleted file.

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
