### PR TITLE
[CARBONDATA-733]Fixed Testcase failure Issue

### PR DESCRIPTION
**Pull request by kumarvishal09**
Fixed test case failure issue in case of V3 format with No inverted index

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/977/

**Comment by chenliang613** [comment]
Tested at my machine, it is failed, please check : 

Tests in error:
  BlockIndexStoreTest.testLoadAndGetTaskIdToSegmentsMapForSingleSegment:85 NullPointer
  BlockIndexStoreTest.testloadAndGetTaskIdToSegmentsMapForDifferentSegmentLoadedConcurrently:180 NullPointer
  BlockIndexStoreTest.testloadAndGetTaskIdToSegmentsMapForSameBlockLoadedConcurrently:120 NullPointer

Tests run: 13, Failures: 0, Errors: 3, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache CarbonData :: Parent ........................ SUCCESS [  3.391 s]
[INFO] Apache CarbonData :: Common ........................ SUCCESS [  3.242 s]
[INFO] Apache CarbonData :: Core .......................... SUCCESS [ 33.859 s]
[INFO] Apache CarbonData :: Processing .................... FAILURE [  9.038 s]

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/979/

**Comment by chenliang613** [comment]
LGTM, verified.

**Pull request closed without merging**
