### PR TITLE
[CARBONDATA-570] clean up carbon-hadoop module

### PR DESCRIPTION
**Pull request by jackylk**
1. remove unused declaration
2. remove redundant exception

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/436/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/438/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/498/

**Comment by QiangCai** [comment]
LGTM

**Comment by chenliang613** [comment]
@jackylk please squash into one commit, i could not merge it.

**Pull request closed without merging**
