### PR TITLE
[CARBONDATA-683] Reduce test time

### PR DESCRIPTION
**Pull request by jackylk**
Reduce test time by:
1. remove all unnecessary print
2. make sample csv file size smaller
3. change logger.audit to initialize strings in constructor

With this PR, mvn clean verify in my local laptop is reduced by 20%

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/772/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/773/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/776/

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
