### PR TITLE
[CARBONDATA-989] decompress error while load 'gz' and 'bz2' data into table

### PR DESCRIPTION
**Pull request by ranmx**
When decompress 'gz' and 'bz2' file through LOAD DATA command, exception occurs:
java.lang.NullPointerException
	at org.apache.hadoop.io.compress.bzip2.Bzip2Factory.isNativeBzip2Loaded(Bzip2Factory.java:54)

This is due to the fact that the decompress codec should be configured while building.
I modified the code to add configuration before building codec object and tested with my real data.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1807/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1821/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1824/

**Pull request closed without merging**
