### PR TITLE
[CARBONDATA-608]Fixed compilation issue in Spark1.6

### PR DESCRIPTION
**Pull request by ravipesala**
Fixed compilation issue in Spark1.6

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/503/

**Comment by chenliang613** [comment]
LGTM

**Comment by zzcclp** [comment]
I complied carbondata with spark-1.6 and this pr,  it is successful. Good.

**Comment by zzcclp** [comment]
When this PR will be merged? @chenliang613 @ravipesala

**Comment by jackylk** [comment]
@chenliang613 I think this PR only solves compilation error for spark1.6, test case is failing because of data update/delete feature. Those need to be solved in another PR.

**Pull request closed without merging**
