### PR TITLE
[CARBONDATA-881] Load status is successful even though system is fail to write status into tablestatus file

### PR DESCRIPTION
**Pull request by mohammadshahidkhan**

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1492/

**Comment by ravipesala** [comment]
LGTM

**Comment by ravipesala** [comment]
@mohammadshahidkhan Please check all caller methods of `writeLoadDetailsIntoFile` and do exception handling there also, otherwise same issue happens if they catch the error and just log it.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1595/

**Comment by mohammadshahidkhan** [comment]
fixed other places also

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1598/

**Comment by ravipesala** [comment]
Please handle at SegmentStatusManager.updateDeletionStatus as well.

**Comment by mohammadshahidkhan** [comment]
Fixed at all the possible palces

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
