### PR TITLE
[CARBONDATA-582] bugfix of negative number in bucketnumber

### PR DESCRIPTION
**Pull request by anubhav100**
jira issue [CARBONDATA-582]
In carbon data i create a table with number of buckets specified as a negative number
here are the logs
jdbc:hive2://localhost:10000> 
CREATE TABLE BucketTest1111352983(name int,ID string)USING org.apache.spark.sql.CarbonSource OPTIONS("bucketnumber"="-1", "bucketcolumns"="name1");
---------+
Result
---------+
---------+
No rows selected (0.277 seconds)
this is because there is no check whether the bucket number given is positive or not
in hive it gives a error
here are the logs in hive
hive> CREATE TABLE BucketTest1111352983(name int,ID string)USING org.apache.spark.sql.CarbonSource OPTIONS("bucketnumber"="-1", "bucketcolumns"="name1");
---------+
Result
---------+
---------+
No rows selected (0.277 seconds)
in carbon data as well it should not allow this

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/391/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/395/

**Comment by ravipesala** [comment]
@anubhav100 Why there are lot of other file changes to fix this issue? Could you explain how you are trying to fix this issue?

**Comment by anubhav100** [comment]
@ravipesala one file is test file table bucketing test and in other file i simply validate whether the bucketNumber contains - or not if it conatins - i throws a exception files are carbonsql parser and carbon source

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/514/

**Comment by ravipesala** [comment]
Can you make both the builds green

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/524/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/525/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/527/

**Pull request closed without merging**
