### PR TITLE
[CARBONDATA-395] Test cases added for Scan Package

### PR DESCRIPTION
**Pull request by deepakmehra10**

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
retest this please

**Comment by ravipesala** [comment]
Please rebase it

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/82/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/83/

**Comment by ravipesala** [comment]
@deepakmehra10 Please rename the title from [Carbondata 395]  to [CARBONDATA-395]

**Comment by ravipesala** [comment]
LGTM

**Comment by ravipesala** [comment]
@deepakmehra10 Why Testdb.carbon, fileName.csv.inprogress and  fileName.log.inprogress are added?

**Comment by deepakmehra10** [comment]
Unnecessary files were deleted ,Please review.

**Comment by deepakmehra10** [comment]
Unnecessary files were deleted , Please review the changes done.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/113/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
