### PR TITLE
[CARBONDATA-981] Get HIVE_CONNECTION_URL from sparkContext.hadoopConfiguration

### PR DESCRIPTION
**Pull request by QiangCai**
Root Cause:
In yarn-client, default configuration can not find HIVE_CONNECTION_URL. But  sparkContext.hadoopConfiguration contain this parameter.
Modification:
change to get HIVE_CONNECTION_URL from sparkContext.hadoopConfiguration

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1775/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1778/

**Comment by chenliang613** [comment]
@allwefantasy  please review this PR

**Comment by allwefantasy** [comment]
LGTM  @chenliang613

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
