### PR TITLE
[CARBONDATA-496] - Created the test cases for carbon datastore

### PR DESCRIPTION
**Pull request by HarshSharma8**

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
ok to test

**Comment by chenliang613** [comment]
@HarshSharma8  please correct the PR title as per https://cwiki.apache.org/confluence/display/CARBONDATA/Contributing+to+CarbonData?src=contextnavpagetreemode

[CARBONDATA-issue number>] Title of the pull request

**Comment by CarbonDataQA** [comment]
Build Success, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/34/

**Comment by HarshSharma8** [comment]
Ok Liang, its done !!


Thank You


Best Regards |
*Harsh Sharma*
Sr. Software Consultant
Facebook <https://www.facebook.com/harsh.sharma.161446> | Twitter
<https://twitter.com/harsh_sharma5> | Linked In
<https://www.linkedin.com/in/harsh-sharma-0a08a1b0?trk=hp-identity-name>
harshs316@gmail.com
Skype*: khandal60*
*+91-8447307237*

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
