### PR TITLE
[CARBONDATA-842]implement CarbonRowDataWriterProcessorStepImpl for no SORT_COLUMN

### PR DESCRIPTION
**Pull request by QiangCai**
When SORT_COLUMNS is empty,  the table is unsorted.
For unsorted table:
1. remove NoSortProcessorStepImpl
2. implement CarbonRowDataWriterProcessorStepImpl

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1454/

**Comment by jackylk** [comment]
Are you merging the sort step and write step in this PR?
I think it is better to merge the row transform part from sort step into write step only, and still have an independent sort step, which is optional. This will be more flexible, different sorter can be replaced independently.

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1458/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1465/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1497/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1501/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
