### PR TITLE
[CARBONDATA-465] Spark streaming dataframe support

### PR DESCRIPTION
**Pull request by allwefantasy**
1. mvn clean verify have already been passed locally.
2. No new unit test cases are added
3. Tested in streamingpro project.
4. Remove kettle clearly.
5. @ravipesala 's pr333 ( https://github.com/apache/incubator-carbondata/pull/333 ) have been merged into this PR

### CODE REVIEW

**Comment by jackylk** [comment]
Why include PR333 in this PR? Does it depends on PR333?

**Comment by allwefantasy** [comment]
I am not sure whether it depends on PR333。I try to resolve issues when carbondata working with Spark Streaming by Merging PR333   however  it does not work. Maybe I should remove the PR333 later.

**Comment by allwefantasy** [comment]
Can we  merge PR333 first then merge this  PR?

**Comment by jackylk** [comment]
I think @ravipesala is still working on #333

**Comment by allwefantasy** [comment]
Ok, i will remove the PR333

**Pull request closed without merging**
