### PR TITLE
[CARBONDATA-607] Cleanup ValueCompressionHolder class and all sub-classes

### PR DESCRIPTION
**Pull request by JihongMA**
1. Rewrite ValueCompressionHolder class as a base class for compressing or uncompressing numeric data for measurement column chunk.

2. Refactor all sub-classes under
org.apache.carbondata.core.datastorage.store.compression.decimal.*
org.apache.carbondata.core.datastorage.store.compression.nonDecimal.*
org.apache.carbondata.core.datastorage.store.compression.none.*
org.apache.carbondata.core.datastorage.store.compression.type.*

3. fix performance bug by avoiding creating unnecessary compress/uncompres value holder during compression or decompression.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/499/

**Comment by ravipesala** [comment]
@JihongMA Please rebase

**Comment by JihongMA** [comment]
@ravipesala I looked at the code conflicted/introduced by the other PR, the new method introduced in the base & sub-classes are not proper abstraction again,  I am going to cleanup those new code as part of rebase.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/546/

**Comment by JihongMA** [comment]
please review promptly! this is pretty tedious rebase and cleanup.

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
