### PR TITLE
[CARBONDATA-909] Added option to specify single pass load in data frame

### PR DESCRIPTION
**Pull request by sanoj-mg**
Added single pass load option  in data frame writer ( spark 1.6 )

Tested with HDP 2.5 / Spark 1.6

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1600/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1617/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1618/

**Comment by ravipesala** [comment]
LGTM, thanks for working on this.

**Comment by ravipesala** [comment]
Please raise a PR on master.

**Comment by sanoj-mg** [comment]
A related PR #786 was merged into 12-dev, due to code freeze for 1.1 release (see #769). Any planned date for 12-dev to be merged into master? It will be easier to merge this after #786.

**Comment by jackylk** [comment]
LGTM

**Pull request merged**
