### PR TITLE
[CARBONDATA-435] improved integration test-case for AllDataTypesTestCase4

### PR DESCRIPTION
**Pull request by rahulforallp**

### CODE REVIEW

**Comment by ravipesala** [comment]
Compilation is failing in integration testcase module, Please fix it.

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by rahulforallp** [comment]
@ravipesala the error has been resolved and merged in PR- #340 . now this branch has been updated .
Please Have look to merge it.

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
