### PR TITLE
[CARBONDATA-696] Fixed Null Pointer Exception for double data type without fraction

### PR DESCRIPTION
**Pull request by kunal642**
Fixed null pointer exception for double data type
Removed unused methods

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1317/

**Comment by kunal642** [comment]
@kumarvishal09 review this please

**Comment by kumarvishal09** [comment]
Please add test case for failure scenario

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1328/

**Comment by kumarvishal09** [comment]
LGTM

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
