### PR TITLE
[CARBONDATA-664] OR condition filter query failing due unloaded dicti…

### PR DESCRIPTION
**Pull request by mohammadshahidkhan**
**Problem**
OR condition filter query failing due unloaded dictionaryDataChucnk and measureDataChunck for projected dimension and measure
**Solution**
We will load the dimensionColumnDataChunk and measureColumnDataChunk of the not loaded 
projected dimension and measure.

### CODE REVIEW

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/753/

**Comment by ravipesala** [comment]
This issue has been handled in PR https://github.com/apache/incubator-carbondata/pull/584,  Please close it.

**Comment by mohammadshahidkhan** [comment]
handled in https://github.com/apache/incubator-carbondata/pull/584

**Pull request closed without merging**
