### PR TITLE
[CARBONDATA-474] test case for columnar package and manage package for filesystem

### PR DESCRIPTION
**Pull request by anuragknoldus**
Implement test case for columnar package and manage packaging for file-system project

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/108/

**Comment by ravipesala** [comment]
LGTM

**Comment by zzcclp** [comment]
@anuragknoldus  @ravipesala The declared package of these four java files must be modidied to "org.apache.carbondata.core.datastorage.store.filesystem":
AlluxioCarbonFileTest.java
HDFSCarbonFileTest.java
LocalCarbonFileTest.java
ViewFsCarbonFileTest.java

**Comment by zzcclp** [comment]
ping @anuragknoldus @ravipesala

**Comment by zzcclp** [comment]
@anuragknoldus @ravipesala I have created a [pr](https://github.com/apache/incubator-carbondata/pull/426) for wrong declared package

**Pull request closed without merging**
