### PR TITLE
[CARBONDATA-390] Support for float datatype

### PR DESCRIPTION
**Pull request by phalodi**
- Support the float dataype in carbon file format
- Run all unit test cases and sucess build with 1.6 and 2.1
- Run style checks to remove checks errors.
- Make changes in Example for float datatype in spark 1.6 and 2.1

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/555/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/556/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/557/

**Comment by ravipesala** [comment]
@phalodi Please rebase the code

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/583/

**Comment by phalodi** [comment]
@ravipesala rebased the branch with master please review it.

**Comment by ravipesala** [comment]
@phalodi can you some testcases(with and with out filter on float datatype) on spark-common-test module

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/621/

**Comment by phalodi** [comment]
@ravipesala I added the unit testcases for float datatype with filter and agg function and also add example for it. Can you please once review it.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/622/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
