### PR TITLE
[CARBONDATA-692]Supporting scalar subquery in carbon

### PR DESCRIPTION
**Pull request by ravipesala**
Scalar subqueries like below not working in carbon.

```
select sum(salary) from scalarsubquery t1
where ID < (select sum(ID) from scalarsubquery t2 where t1.name = t2.name
```
Spark optimizes the subquery separately and  it throws error if it find decoder in it. So now this PR fixes to avoid optimizing the separately and only optimize whole query once

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/807/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/808/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/809/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/810/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/813/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
