### PR TITLE
correct possible errors in test cases when file is not present at the location

### PR DESCRIPTION
**Pull request by sraghunandan**
Added exception handling for getResource returning null

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/392/

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
