### PR TITLE
[CARBONDATA-533] Written the unit test cases for carbondata-processing.newFlow.steps package

### PR DESCRIPTION
**Pull request by HarshSharma8**
Written the unit test cases in **carbondata-processing.newFlow.steps** package for the following classes,

- SortProcessorStepImpl,
- DataWriterProcessorStepImpl	,
- DataConverterProcessorStepImpl

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by jackylk** [comment]
Please modify the description of this PR

**Comment by HarshSharma8** [comment]
Modified the PR, please have a look.


Thank You


Best Regards |
*Harsh Sharma*
Sr. Software Consultant
Facebook <https://www.facebook.com/harsh.sharma.161446> | Twitter
<https://twitter.com/harsh_sharma5> | Linked In
<https://www.linkedin.com/in/harsh-sharma-0a08a1b0?trk=hp-identity-name>
harshs316@gmail.com
Skype*: khandal60*
*+91-8447307237*

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/209/

**Comment by jackylk** [comment]
I do not think adding unit test for these steps are good testcase, because these steps will change easily when adding new feature. We should be adding test case for writing and reading CarbonData files (file level features) or loading and query tables (table level features)

**Pull request closed without merging**
