### PR TITLE
[CARBONDATA - 878] Fixed Formatting Issues in document quick-start-guide.md

### PR DESCRIPTION
**Pull request by ksimar**
Fixed Formatting Issues in document quick-start-guide.md

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by chenliang613** [comment]
Two comments:
1. The pr title is not correct.
2.Can you explain why need to reformat the document ?

**Comment by ksimar** [comment]
@chenliang613 
1) PR title is corrected.
2) This PR Fixes the inconsistent styling issues in the quick-start-guide.md document.

**Comment by chenliang613** [comment]
Please update the title, how about : 
[CARBONDATA - 878]  Fixed Formatting Issues in document quick-start-guide.md

**Comment by ksimar** [comment]
@chenliang613 Updated the title. Please review the PR.

**Pull request closed without merging**
