### PR TITLE
[CARBONDATA-674]Fixed Compatibility issue

### PR DESCRIPTION
**Pull request by kumarvishal09**
Problem: Query is not working with old store
Solution: As big decimal compression is added in new flow we need to add  handle old store

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/730/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/731/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/732/

**Comment by ravipesala** [comment]
LGTM

**Pull request merged**
