### PR TITLE
[CARBONDATA-238]CarbonOptimizer shouldn't add CarbonDictionaryCatalystDecoder for HiveTable

### PR DESCRIPTION
**Pull request by QiangCai**
**Root Cause Analysis:** 
When carbon table union hive table, CarbonOptimizer will add CarbonDictionaryCatalystDecoder for all tables.

**Solution:**
If the child logical plan doesn't contain CarbonRelation, no need to add CarbonDictionaryCatalystDecoder

### CODE REVIEW

**Comment by QiangCai** [comment]
CI PASS
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/198/

**Comment by ashokblend** [comment]
looks good, please add test case.

**Comment by QiangCai** [comment]
@ashokblend 
Added test case, please review.

**Comment by QiangCai** [comment]
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/274/
CI PASS

**Comment by QiangCai** [comment]
I will raise another pr to fixed this issue.

**Pull request closed without merging**
