### PR TITLE
[CARBONDATA-669] InsertIntoCarbonTableTestCase.insert into carbon table from carbon table union query random test failure

### PR DESCRIPTION
**Pull request by mohammadshahidkhan**
added prefetch in B-Tree loading.
Previously we were putting the dummy object in the cache the we were building the b-tree.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/693/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/694/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/705/

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/707/

**Comment by gvramana** [comment]
LGTM please raise an issue

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/713/

**Comment by gvramana** [comment]
It is already merged to master please close this PR.

**Pull request closed without merging**
