### PR TITLE
[CARBONDATA-684] Improve Tests and Coverage For Core Module

### PR DESCRIPTION
**Pull request by Vimal-Das**
Added tests to improve the test sufficiency and coverage for:-

- The dictionary generators
- The dictionary client and server

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/774/

**Comment by jackylk** [comment]
@Vimal-Das Actually I am about to change the implementation for dictionary client server to use netty4. I think it is better to wait for some time after the new implementation PR is raised

**Comment by Vimal-Das** [comment]
@jackylk Will the interface between the client and the server also change while changing the implementation? 
If yes, I shall raise a new PR excluding the client-server tests.
If no, then the implementation changes should not impact the client-server tests.

**Comment by Vimal-Das** [comment]
Retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/777/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/778/

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/952/

**Comment by ravipesala** [comment]
@Vimal-Das can you fix compile errors as per latest code.

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/974/

**Comment by Vimal-Das** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/976/

**Comment by Vimal-Das** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/978/

**Comment by chenliang613** [comment]
retest this please

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1000/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
