### PR TITLE
Clean up CarbonUtil

### PR DESCRIPTION
**Pull request by jarray888**
Clean up code

### CODE REVIEW

**Comment by jarray888** [comment]
test this please

**Comment by jackylk** [comment]
LGTM

**Comment by jarray888** [comment]
ok to test

**Comment by CarbonDataQA** [comment]
Build Success, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/50/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
