### PR TITLE
[CARBONDATA-472] Added unit test for cache package

### PR DESCRIPTION
**Pull request by kunal642**
Added unit test for CarbonLRUCache
Added unit test for ColumnDictionaryChunkIterator
Added unit test for ColumnReverseDictionaryInfo
Added unit test for DictionaryCacheLoaderImpl
Updated unit tests for DictionaryChunksWrapper

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/80/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
