### PR TITLE
[CARBONDATA-475] Added test cases for org.apache.carbondata.core.carbon.querystatistics

### PR DESCRIPTION
**Pull request by anubhav100**

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
@anubhav100 Please rename PR title from [Carbondata 475] to [CARBONDATA-475]

**Comment by anubhav100** [comment]
@ravipesala i renamed it

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/109/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
