### PR TITLE
[CARBONDATA-374] support smallint

### PR DESCRIPTION
**Pull request by cenyuhai**
**What changes were proposed in this pull request?**

support smallint type

**How to test？**
Test with TestLoadDataWithHiveSyntax.scala

### CODE REVIEW

**Comment by cenyuhai** [comment]
@jackylk @lion-x pls review the codes

**Comment by ravipesala** [comment]
@cenyuhai There is one testcase failing, please fix it.
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/748/

**Comment by chenliang613** [comment]
错误信息如下：
**Regression**
org.apache.carbondata.core.util.DataTypeUtilTest.testGetDataType

Failing for the past 1 build (Since Unstable#748 )
运行时间：3 毫秒
Error Message

expected:<SHORT> but was:<STRING>
Stacktrace

junit.framework.AssertionFailedError: expected:<SHORT> but was:<STRING>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:86)
	at junit.framework.TestCase.assertEquals(TestCase.java:253)
	at org.apache.carbondata.core.util.DataTypeUtilTest.testGetDataType(DataTypeUtilTest.java:82)

**Comment by cenyuhai** [comment]
@ravipesala @chenliang613

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
