### PR TITLE
[CARBONDATA-968] Alter temp store location and decimal data type incorrect result display correction

### PR DESCRIPTION
**Pull request by manishgupta88**
Changes done:
1. Corrected temp store location path formation for compaction through sort step.
2. Correct filter query bug on datatype changed for a decimal column.
3. Corrected data type change validations. New precision should always be greater than existing precision and new scale value can be same as old scale value.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1723/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1727/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1728/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
