### PR TITLE
[Carbondata 434] Improved integration test cases for AllDataTypesTestCase2

### PR DESCRIPTION
**Pull request by anubhav100**

### CODE REVIEW

**Comment by anubhav100** [comment]
@ravipesala i removed duplicate test cases from AllDataTypeCase2 please have a look

**Comment by ravipesala** [comment]
Please rebase the code, don't let other commits come to this PR.

**Comment by anubhav100** [comment]
@ravipesala i rebased the code and there is one correction becuase of which your build of integration test case will be failing here return keyword is missing in query test:  |$e
               |${org.apache.spark.sql.catalyst.util.stackTraceToString(e)}
            """.stripMargin
 -        Some(errorMessage)
 +       return Some(errorMessage)
      }
  
      if (prepareAnswer(expectedAnswer) != prepareAnswer(sparkAnswer)) {
 @@ -157,7 +157,7 @@ object QueryTest {
                prepareAnswer(sparkAnswer).map(_.toString())).mkString("\n")
          }
        """.stripMargin
 -      Some(errorMessage)
 +      return Some(errorMessage)
      } i corrected this in this pr first you need to merge this pr before merging other pr for integration test cases otherwise there will be compilation errors

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
