### PR TITLE
[CARBONDATA-815] add hive integration for carbon

### PR DESCRIPTION
**Pull request by cenyuhai**
add basic hive integration for carbon

### CODE REVIEW

**Comment by cenyuhai** [comment]
@QiangCai @chenliang613

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1449/

**Comment by chenliang613** [comment]
@cenyuhai  please add [CARBONDATA-815] for the PR title.

**Comment by QiangCai** [comment]
LGTM

**Pull request closed without merging**
