### PR TITLE
[CARBONDATA-673]Reverting big decimal compression as it has below issue

### PR DESCRIPTION
**Pull request by ashokblend**
**Problem**
We had added code for big decimal compression for tpc-h activity. It turns out there is data inaccuracy when big decimal scale value is more then 18 then result is not accurate

**Solution**
Revert the code to old way

**TO-DO**
Find another way to compress big decimal data type.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/700/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/710/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/718/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/719/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/723/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/727/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
