### PR TITLE
[CARBONDATA-690]Fix load fail with unsafe enabled and with bigdecimal datatypes

### PR DESCRIPTION
**Pull request by ravipesala**
Load fails when columns have big decimal datatypes in unsafe mode. This PR fixes it.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/812/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/833/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/854/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/904/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
