### PR TITLE
[CARBONDATA-812] make vectorized reader as default reader

### PR DESCRIPTION
**Pull request by jackylk**
change property for vectorized reader to true

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1306/

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1322/

**Comment by ravipesala** [comment]
LGTM. Testcases failing in this PR is fixed in PR https://github.com/apache/incubator-carbondata/pull/700

**Pull request closed without merging**
