### PR TITLE
[CARBONDATA-732] Exclude netty dependencies in assembly module

### PR DESCRIPTION
**Pull request by PKOfficial**

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1084/

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1086/

**Comment by jackylk** [comment]
LGTM

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
