### PR TITLE
[CARBONDATA 524] AllDataypeTestCase5 improved

### PR DESCRIPTION
**Pull request by rahulforallp**

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by rahulforallp** [comment]
this build fail cause has been already resolved in  PR: #421 .

**Comment by ravipesala** [comment]
@rahulforallp Please rename title from [Carbondata 524] to [CARBONDATA-524]

**Comment by rahulforallp** [comment]
@ravipesala  title renamed

**Comment by ravipesala** [comment]
@rahulforallp  the title name must be the jira issue Id, so it has to be CARBONDATA-524 not CARBONDATA 524.
Please follow this rule in future PR's

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
