### PR TITLE
[CARBONDATA-874] Fixed order by limit with select * query

### PR DESCRIPTION
**Pull request by ravipesala**
Order by limit with select * from query is not working as the it uses `TakeOrderedAndProjectExec`  internally and it try to get the output from logical plan instead of physical plan. So incase of logical releation we need to update the dictionary attributes with integer type.

### CODE REVIEW

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1418/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1425/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1426/

**Comment by kumarvishal09** [comment]
LGTM

**Pull request closed without merging**
