### PR TITLE
[CARBONDATA-474] Added test Cases for Datastorage.Impl Module

### PR DESCRIPTION
**Pull request by anubhav100**

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
ok to test

**Comment by ravipesala** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://136.243.101.176:8080//job/ApacheCarbonPRBuilder/27/
Build Success, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/

**Comment by ravipesala** [comment]
retest this please

**Comment by ravipesala** [comment]
@anubhav100 Please rename the title [Carbondata -474]  to [CARBONDATA-474]

**Comment by anubhav100** [comment]
@ravipesala i renamed it

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/111/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
