### PR TITLE
[CARBONDATA-865] Remove configurations for Kettle from installation-guide.md

### PR DESCRIPTION
**Pull request by manojmathpal**

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1440/

**Comment by chenliang613** [comment]
LGTM, thanks for your contributing.
Indeed, by default the data loading will not use kettle, so the cluster installation document can remove kettle part.

**Pull request closed without merging**
