### PR TITLE
[CARBONDATA - 483] Added unit test cases for core.carbon.metadata package

### PR DESCRIPTION
**Pull request by geetikagupta16**

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
ok to test

**Comment by ravipesala** [comment]
Build Success, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/29/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/67/

**Pull request closed without merging**
