### PR TITLE
[CARBONDATA-269]change delete segment syntax

### PR DESCRIPTION
**Pull request by Jay357089**
https://issues.apache.org/jira/browse/CARBONDATA-269

### CODE REVIEW

**Comment by Jay357089** [comment]
CI passed
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/313/

**Comment by jackylk** [comment]
What is the new proposed syntax here?

**Comment by Jay357089** [comment]
@ManoharVanam  done and CI passed. http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/315/

**Comment by ManoharVanam** [comment]
Please update all related .md files .

**Comment by Jay357089** [comment]
need more discussion. close for now.

**Pull request closed without merging**
