### PR TITLE
[CARBONDATA-611] Make the default maven command work with build-with-format profile

### PR DESCRIPTION
**Pull request by ravipesala**
Currently `mvn clean -Pbuild-with-format package` does not work, so this PR fixes it, And also by default the assembly jar includes all spark and hadoop jars, this PR removes these dependencies from the assembly jar by default.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/515/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/519/

**Comment by QiangCai** [comment]
@ravipesala 
In my opinion, If some profile is active by default and only contains some property elements, we can remove this profile and add these property elements into properties element.
For assembly/pom.xml, I prefer to add these three provided property elements into properties element, but not each profile.

**Comment by chenliang613** [comment]
please delete the below duplicated properties:
<id>spark-1.5</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties> -- delete
        <spark.version>1.5.2</spark.version> --delete
        <scala.binary.version>2.10</scala.binary.version> --delete
        <scala.version>2.10.4</scala.version> --delete
      </properties> --delete
      <modules>
        <module>integration/spark</module>
        <module>examples/spark</module>
      </modules>

**Comment by QiangCai** [comment]
LGTM

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/520/

**Pull request closed without merging**
