### PR TITLE
Show query statistics as millseconds instead of seconds

### PR DESCRIPTION
**Pull request by foryou2030**
# Why raised this PR?

It is more proper to show time cost of statistics as millseconds instead of seconds

### CODE REVIEW

**Comment by foryou2030** [comment]
CI passed
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/137/

**Comment by sraghunandan** [comment]
Executor statistics are handled in milliseconds?can u pls put the ref code

**Comment by sujith71955** [comment]
LGTM

**Comment by foryou2030** [comment]
@sraghunandan , yes, pls  check the QueryStatistics class

```
  public QueryStatistic() {
    this.startTime = System.currentTimeMillis();
  }
```

**Comment by gvramana** [comment]
LGTM

**Pull request closed without merging**
