### PR TITLE
[CARBONDATA-804] Update file structure info as per V3 format definition

### PR DESCRIPTION
**Pull request by chenliang613**
The master has merged new V3 format for improving performance, this PR is for updating file structure info as per V3 format definition.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1285/

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1287/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
