### PR TITLE
[CARBONDATA-1005] Fixed dataloading less number of rows than actual rows when data size is multiples of page size.

### PR DESCRIPTION
**Pull request by ravipesala**
Data load does not load all rows when data size is multiples of page size. 
The page size of data load is 32000 , so if my data size is multiples 32000 like 64000 then it cannot load all data

It is because in finish step it does not take care the pages which are already existed in memory.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1843/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1850/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1854/

**Comment by jackylk** [comment]
LGTM

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1869/

**Comment by jackylk** [comment]
testcase failed

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1876/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
