### PR TITLE
[CARBONDATA-197]Changed List To Queue for storing block execution infos

### PR DESCRIPTION
**Pull request by kumarvishal09**
Problem: we are maintaining block execution infos for each block in a list and in detail query executor we are removing it for execution. If number of infos in list is more than removal will be time taking operation as we are removing from to top index and it will sink every time.
Solution:Queue will be proper data structure for this scenario

### CODE REVIEW

**Comment by kumarvishal09** [comment]
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/71/

**Comment by ravipesala** [comment]
@kumarvishal09 Can you `PerfTest` in examples. It throws some exception as below.
```
java.lang.NullPointerException
	at org.apache.carbondata.scan.result.iterator.AbstractDetailQueryResultIterator.intialiseInfos(AbstractDetailQueryResultIterator.java:95)
	at org.apache.carbondata.scan.result.iterator.AbstractDetailQueryResultIterator.<init>(AbstractDetailQueryResultIterator.java:87)
	at org.apache.carbondata.scan.result.iterator.DetailQueryResultIterator.<init>(DetailQueryResultIterator.java:47)
```

**Comment by kumarvishal09** [comment]
ok i will check

**Comment by kumarvishal09** [comment]
@ravipesala I tested with list implementation, there also its failing. I think its a different issue can you please check in your environment with older code and let me know its failing or not.

**Comment by ravipesala** [comment]
@kumarvishal09 Please rebase it

**Comment by kumarvishal09** [comment]
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/126/

**Comment by ravipesala** [comment]
Build Failed, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/

**Pull request closed without merging**
