### PR TITLE
[CARBONDATA-936][WIP]parse hash partition table

### PR DESCRIPTION
**Pull request by lionelcao**
parse ddl to get partition info and store in TableModel

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1782/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1784/

**Comment by QiangCai** [comment]
@lionelcao please fix the error in CI.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1816/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1817/

**Comment by QiangCai** [comment]
@lionelcao please add list and range partition.

**Pull request closed without merging**
