### PR TITLE
[CARBONDATA-483] Added unit test cases for core.carbon.metadata package

### PR DESCRIPTION
**Pull request by geetikagupta16**

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by ravipesala** [comment]
@geetikagupta16 Please rename PR title from [CARBONDATA - 483]  to [CARBONDATA-483]

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/110/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
