### PR TITLE
[Carbondata-371] Write unit test for ColumnDictionaryInfo

### PR DESCRIPTION
**Pull request by harmeetsingh0013**
Unit test cases for class file org.apache.carbondata.core.cache.dictionary.ColumnDictionaryInfo.java

### CODE REVIEW

**Comment by harmeetsingh0013** [comment]
Hello, @ravipesala please review this PR.

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by harmeetsingh0013** [comment]
yes @ravipesala , Is there any problem?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/78/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
