### PR TITLE
[CARBONDATA-512] Make timestamp formatter static and thread safe

### PR DESCRIPTION
**Pull request by jackylk**
In DataTypeUtil.java, carbon is creating a SimpleDateFormat for every row, which creates too many objects.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/61/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/62/

**Comment by scwf** [comment]
LGTM

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
