### PR TITLE
[CARBONDATA-811] Refactor result collector class

### PR DESCRIPTION
**Pull request by thotasrinath**
**Problem**: For each batch result collector class is filling all the class level variable this may hit the performance
**Solution**: fill it in constructor, so only once it will be initialize.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1305/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1307/

**Pull request closed without merging**
