### PR TITLE
[MINOR-FIX]change the declared package of these four java files 

### PR DESCRIPTION
**Pull request by zzcclp**
The declared package of these four java files must be modidied to "org.apache.carbondata.core.datastorage.store.filesystem":
AlluxioCarbonFileTest.java
HDFSCarbonFileTest.java
LocalCarbonFileTest.java
ViewFsCarbonFileTest.java

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by jackylk** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/140/

**Comment by jackylk** [comment]
LGTM, all testcase passed

**Comment by zzcclp** [comment]
thanks, @jackylk .

**Pull request closed without merging**
