### PR TITLE
[CARBONDATA-323] load data not support local

### PR DESCRIPTION
**Pull request by scwf**
Seems we do not support `load data local`, so fix it.

### CODE REVIEW

**Comment by kumarvishal09** [comment]
Can u tell me the load query.

**Comment by scwf** [comment]
@kumarvishal09 in the parser   `opt(LOCAL) ~>`  this option never used.

**Comment by Vimal-Das** [comment]
@scwf Can you add test case as well for the LOCAL scenario.

**Comment by scwf** [comment]
@Vimal-Das  from the sytax carbon could not support local, it is necessary to add a test for this?

**Comment by jackylk** [comment]
Yes, local is not supported. But your modification may intoduce incompatibility, can you modify it as parsing failure (unsupported feature) in case of local?

**Comment by scwf** [comment]
It will parsing failure with this modification.

**Comment by jackylk** [comment]
Thanks, and please fire a Jira issue and add it to the PR title

**Comment by scwf** [comment]
And i do not think this is related to compatibility, actually now the `load data local` is wrong in syntax since the load action is not done from local data. If users have used the syntax, they just used a wrong syntax that not run as they expected, we should fix this.

**Comment by jackylk** [comment]
Agree. Please fire a Jira issue. Thanks for fixing it.

**Comment by scwf** [comment]
ok, later file a jira for this issue:)

**Comment by scwf** [comment]
@jackylk carbon did not have a jenkens for CI

**Comment by jackylk** [comment]
@scwf please refer to other PR how they do it.
Apache CI is not ready for Carbon yet, meanwhile we have setup a CI enviornment in India as a temporary solution, please use this [CI] (http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/)

modify your PR number and paste the result in your PR

**Comment by chenliang613** [comment]
@scwf Thanks for your PR
please find the CI result : http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/470/
There are two errors.

**Comment by Zhangshunyu** [comment]
There are 2 test cases in TestLoadDataWithFileHeaderException file，who used the ddl including “local”，pls also delete the local in them，so that the test case can pass.

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by scwf** [comment]
i will close this, and in spark2 integration we do not support load local for carbon, in spark1 i think there is no problem

**Pull request closed without merging**
