### PR TITLE
[CARBONDATA-286] Support Append mode when writing Dataframe to CarbonData

### PR DESCRIPTION
**Pull request by jackylk**
Support df.write using Append as save mode, it will become a new segment in CarbonData
This PR add append implementation and modified DataframeAPIExample to show the usage.

### CODE REVIEW

**Comment by jackylk** [comment]
CI passed
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/371/

**Comment by ravipesala** [comment]
When using `Overwrite` I think it fails now when table already exists. But it should clean the old data from old table and load the data right?

**Comment by jackylk** [comment]
@ravipesala I think it works, when processing for `Overwrite`, it first drop the table then create the table again. And I added a test case for it, see `test("test overwrite")`

**Comment by ravipesala** [comment]
LGTM

**Comment by ravipesala** [comment]
@jackylk can you squash commits. I am not able to squash it.

**Comment by jackylk** [comment]
CI passed
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/439/

**Comment by ravipesala** [comment]
LGTM

**Pull request merged**
