### PR TITLE
Update Quick-Start.md

### PR DESCRIPTION
**Pull request by xiaoyesoso**
https://issues.apache.org/jira/browse/CARBONDATA-81

### CODE REVIEW

**Comment by chenliang613** [comment]
@ravipesala  please review

**Comment by Zhangshunyu** [comment]
Is this parameter "spark.carbon.storepath" exist?

**Comment by chenliang613** [comment]
@Zhangshunyu ,  yes. this parameter is for users to set their own store directory.

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
