### PR TITLE
[CARBONDATA-218]Remove  dependency: spark-csv

### PR DESCRIPTION
**Pull request by QiangCai**
- Remove  dependency: spark-csv 
- Unify CSV reader for dict generation and dataloading

### CODE REVIEW

**Comment by ravipesala** [comment]
@QiangCai May not be right time to do changes in data loading part now, as we are working on removing kettle and changing the design of loading data. we already consider of removing dependency of spark-csv  and unifying of csv reader through inputformat.

**Comment by QiangCai** [comment]
@ravipesala 
We can extract a new Inputformat  and RecordReader in the future.

Now it is neccessary to unify Csv reader.
1. Remove code which copied from spark-csv
2. Just need one reader and one parser.

**Comment by QiangCai** [comment]
CI PASS
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/140

**Comment by jackylk** [comment]
@ravipesala 
I feel that it is OK to remove spark-csv dependency if it fits in our effort towards removing kettel and changing data loading design. 

I will do one round of review and undertand what QiangCai has done.

**Comment by jackylk** [comment]
@QiangCai please rebase

**Comment by QiangCai** [comment]
Close this PR.

I have raised another PR #233 to provide CSVInputFormat to unify CSV file reader.

**Pull request closed without merging**
