### PR TITLE
[CARBONDATA-614]Fix issue:  Dictionary file name is locked for updation.

### PR DESCRIPTION
**Pull request by QiangCai**
1.  set carbon property CarbonCommonConstants.STORE_LOCATION for CarbonBlockDistinctValuesCombineRDD and CarbonGlobalDictionaryGenerateRDD to avoid  java.lang.RuntimeException: Dictionary file name is locked for updation. 

2. pass CARBON_TIMESTAMP_FORMAT to executor side from driver side during dcitonary generation

3. fix code style for carbonTableSchema.scala

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/533/

**Comment by QiangCai** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/534/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/535/

**Comment by chenliang613** [comment]
LGTM

**Comment by cyq130** [comment]
I have pulled the latest version carbondata but still encounter this issue. My carbondata version is carbondata_2.10-1.1.0-incubating-SNAPSHOT-shade-hadoop2.7.1.jar.

**Pull request closed without merging**
