### PR TITLE
[CARBONDATA-416] Unit test for result.impl package

### PR DESCRIPTION
**Pull request by kunal642**
Added Unit Test for FilterQueryScannedResult
Added Unit Test for NonFilterQueryScannedResult
Added Unit Test for RestructureUtil

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/76/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
