### PR TITLE
[CARBONDATA-801] Examples syntax fix

### PR DESCRIPTION
**Pull request by thotasrinath**
Updated the document as per the supported syntax.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1319/

**Pull request closed without merging**
