### PR TITLE
[CARBONDATA-460]Added Unit Tests For core.writer.sortindex package

### PR DESCRIPTION
**Pull request by geetikagupta16**

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by ravipesala** [comment]
@geetikagupta16 Please rename title from [CarbonData-460]  to [CARBONDATA-460]

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/97/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
