### PR TITLE
[CARBONDATA-513] reduce new too many BigDecimal

### PR DESCRIPTION
**Pull request by piaoyats**
Currently, we new too many BigDecimal object while scan, we could reduce some unnecessary object allocate

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by jackylk** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/64/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/65/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
