### PR TITLE
[CARBONDATA-555] Configure Integration testcases to be run on hadoop cluster

### PR DESCRIPTION
**Pull request by rahulforallp**
**Profile for local file-source and hadoop file-source  has been added to pom.xml. And properties has been fetched to outputDirectory in > app.properties file to be read later in project.**

**User will need to select profile during run of integration-testcases as follow :**
`**mvn -Plocal -projects integration-testcases clean package**`

**If you want to override URL then :** 
 **`mvn -Phadoop -Dbase-url=YourUrlHere -projects integration-testcases clean package`**

Following file has been changed : 
        -> pom.xml changed
        -> AllDataTypesTestCase1
        -> AllDataTypesTestCase2
        -> AllDataTypesTestCase3
        -> AllDataTypesTestCase4
        -> AllDataTypesTestCase5
        -> AllDataTypesTestCase6

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/326/

**Comment by ravipesala** [comment]
Please rename title from Carbondata 555 to CARBONDATA-555

**Comment by ravipesala** [comment]
And also can you make the integration test cases under integration/spark to work on cluster as well in another PR.

**Comment by rahulforallp** [comment]
@ravipesala ya sure . I will do this in another PR.

**Pull request closed without merging**
