### PR TITLE
[CARBONDATA-791] Exists queries of TPC-DS are failing in carbon.

### PR DESCRIPTION
**Pull request by ravipesala**
Carbon plan fails to handle exists queries. For exists queries plan comes as predicatesubquery and try to resolve the plan individually. We should not resolve the plan individually , we should handle it all at once. So for that purpose added flags in relation.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1218/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1219/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1220/

**Comment by gvramana** [comment]
LGTM

**Pull request closed without merging**
