### PR TITLE
[CARBONDATA-643] All dictionary path issue

### PR DESCRIPTION
**Pull request by ManoharVanam**
Issue : When we are passing Invalid ALL_DICTIONARY_PATH' in load query ,it is throwing null pointer exception.
Solution : We are not validating ALL_DICTIONARY_PATH properly, added path check to validate the same.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/679/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/704/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/706/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
