### PR TITLE
[CARBONDATA-449] Remove unnecessary property when creating Logger

### PR DESCRIPTION
**Pull request by jackylk**
When creating Log object, there are some unnecessary properties.
No functionality is modified in this PR.

### CODE REVIEW

**Comment by ravipesala** [comment]
Build finished.

**Comment by ravipesala** [comment]
test

**Comment by chenliang613** [comment]
ok to test

**Comment by CarbonDataQA** [comment]
Build Success, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/36/

**Comment by CarbonDataQA** [comment]
Build Success, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/37/

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/49/

**Comment by chenliang613** [comment]
i got the below error , please check : 
-------------------------------------------------
[ERROR] /Users/apple/Carbon-dev/mergepr/core/src/test/java/org/apache/carbondata/core/util/DataFileFooterConverterTest.java:[218,9] 对于FileFooter(int,int,java.util.List<org.apache.carbondata.format.ColumnSchema>,org.apache.carbondata.format.SegmentInfo,java.util.List<org.apache.carbondata.format.BlockletIndex>,java.util.List<org.apache.carbondata.format.BlockletInfo>), 找不到合适的构造器
    构造器 org.apache.carbondata.format.FileFooter.FileFooter()不适用
      (实际参数列表和形式参数列表长度不同)
    构造器 org.apache.carbondata.format.FileFooter.FileFooter(int,long,java.util.List<org.apache.carbondata.format.ColumnSchema>,org.apache.carbondata.format.SegmentInfo,java.util.List<org.apache.carbondata.format.BlockletIndex>)不适用
      (实际参数列表和形式参数列表长度不同)
    构造器 org.apache.carbondata.format.FileFooter.FileFooter(org.apache.carbondata.format.FileFooter)不适用
      (实际参数列表和形式参数列表长度不同)
[INFO] 1 error

**Pull request closed without merging**
