### PR TITLE
[CARBONDATA-195] Select query with AND filter failing for empty '' operand value of numeric column

### PR DESCRIPTION
**Pull request by mohammadshahidkhan**
Affected Query syntax:
select * from Table Int_col='' and str_col='';

### CODE REVIEW

**Comment by sujith71955** [comment]
Run the PR builder

**Comment by sujith71955** [comment]
LGTM

**Comment by ravipesala** [comment]
@mohammadshahidkhan can you add test case for this scenerio.

**Comment by mohammadshahidkhan** [comment]
added test case PR build is also passed for the same
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/76/

**Comment by ravipesala** [comment]
LGTM

**Pull request merged**
