### PR TITLE
[CARBONDATA-438] Added unit test for FilterScanner

### PR DESCRIPTION
**Pull request by kunal642**
Added unit test for FilterScanner

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/98/

**Comment by ravipesala** [comment]
@kunal642 There are some compilation issues in testcases, please fix them.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.5.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/116/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
