### PR TITLE
[CARBONDATA-782]support SORT_COLUMNS 

### PR DESCRIPTION
**Pull request by QiangCai**
The tasks of SORT_COLUMNS:

Support create table with sort_columns property.
e.g. tblproperties('sort_columns' = 'col7,col3')
The table with SORT_COLUMNS property will be sorted by SORT_COLUMNS. The order of columns is decided by SORT_COLUMNS.

Change the encoding rule of SORT_COLUMNS
Firstly, the rule of column encoding will keep consistent with previous.
Secondly, if a column of SORT_COLUMNS is a measure before, now this column will be created as a dimension. And this dimension is a no-dicitonary column(Better to use other direct-dictionary).
Thirdly, the dimension of SORT_COLUMNS have RLE and ROWID page, other dimension have only RLE(not sorted).

The start/end key should be composed of SORT_COLUMNS.
Using SORT_COLUMNS to build start/end key during data loading and select query.

### CODE REVIEW

**Comment by QiangCai** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1392/

**Comment by QiangCai** [comment]
@ravipesala @jackylk I raised this new pr based on 12-dev branch.

**Comment by jackylk** [comment]
Can you add the on-going JIRA for this feature, in the CARBONDATA-782 JIRA
others LGTM

**Comment by QiangCai** [comment]
done

**Comment by zzcclp** [comment]
@QiangCai @jackylk will this pr be merged into branch master?

**Comment by jackylk** [comment]
This PR is actually merged into 12-dev which is branch for CarbonData 1.2 development. Master branch now is preparing for 1.1 release, so no new feature will be merged into master until 1.1 is released.

**Comment by zzcclp** [comment]
@jackylk thanks for you reply, in my opinion i think that it's better to create a branch-1.1 for preparing for 1.1 release, and keep branch master as development branch.

**Comment by QiangCai** [comment]
This PR was merged, so I close it.

**Pull request closed without merging**
