### PR TITLE
[CARBONDATA-636]Fixed testcase issues in spark 1.6 and 2.1 of no kettle. And also refactored of insert into flow in no kettle

### PR DESCRIPTION
**Pull request by ravipesala**
Fixed testcase issues in spark 1.6 and 2.1 of no kettle. And also refactored of insert into flow in no kettle

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/570/

**Comment by QiangCai** [comment]
@ravipesala 
In PR 528, I fixed InsertInto issue for kettle flow and move test case to spark-common-test.

**Comment by ravipesala** [comment]
@QiangCai This I have fixed for no kettle flow and refactored code

**Comment by QiangCai** [comment]
@ravipesala 
ok,  no conflict, just need do rebase.
PR528  is for kettle flow in spark2 and move test case to spark-common-test.

**Comment by jackylk** [comment]
@ravipesala Is this PR only fix some of the test case? I used mvn verify -Pno-kettle, but IUD test case is failing. Fix in another PR?

**Comment by ravipesala** [comment]
@jackylk IUD testcase are fixed in https://github.com/apache/incubator-carbondata/pull/523. 
Please merge https://github.com/apache/incubator-carbondata/pull/523 as well.

**Comment by jackylk** [comment]
I will merge this PR now and will wait for @ravikiran23 to fix comment for #523

**Pull request closed without merging**
