### PR TITLE
CARBONDATA-163 Tool to merge Github Pull Requests

### PR DESCRIPTION
**Pull request by ajayyadava**
This tool allows committers to review and merge pull requests and close associated JIRAs.

### CODE REVIEW

**Comment by ravipesala** [comment]
@ajayyadava Thanks for working on this. 
Can you add the steps that how the committer should use this tool?

**Comment by hsaputra** [comment]
+1 for a README to show how to use the tool.

**Comment by chenliang613** [comment]
@ajayyadava  can you provide the README to introduce how to use the tool, thanks.

**Comment by ajayyadava** [comment]
Hello everyone,  
Sorry for delayed response,  the command to execute the script is at the top in comments. Just execute it like normal python script and it will help you set the environment and ask for input at each step. 

Having said that, I agree a Readme will be useful and will be happy to add it for carbondata as well. We(Apache Falcon) have documented it in confluence. Should I add it in confluence or code?

**Comment by ajayyadava** [comment]
@chenliang613  I have added the README in the code. Let me know what do you think.

**Comment by hsaputra** [comment]
+1

LGTM

**Comment by ravipesala** [comment]
+1 LGTM

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
