### PR TITLE
[CARBONDATA-140] Fix all legal headers, add the legal files (NOTICE, …

### PR DESCRIPTION
**Pull request by jbonofre**
Fix all legal headers, add the legal files (NOTICE, DISCLAIMER) and fix LICENSE file

### CODE REVIEW

**Comment by jbonofre** [comment]
Rebase.

By the way, please, to apply do a merge to keep original author, etc. If you don't know how to do that, I can show you.

**Comment by ravipesala** [comment]
LGTM +1
Please help to provide the steps for doing the merge to keep the original author.

**Comment by jbonofre** [comment]
Absolutely: let me merge explaining every step here.

**Comment by jbonofre** [comment]
Prerequisite
---------------
Assuming, you cloned the Apache git repo:

```
git clone https://git-wip-us.apache.org/repos/asf/incubator-carbondata
```

I advise to rename origin remote as apache:

```
git remote rename origin apache
```

Now, let's add the github remote:

```
git remote add github https://github.com/apache/incubator-carbondata
```

For convenience, we add a new fetch reference for the pull requests:

```
git config --local --add remote.github.fetch '+refs/pull/*/head:refs/remotes/github/pr/*'
```

Then, we can fetch all, including the pull requests:

```
git fetch --all
```

Pull Request Branch
---------------------------
Now, we are ready to checkout a pull request in a specific branch:

```
git checkout -b pr-63 github/pr/63
```

You are now on the pull request (#63) branch: you can review and test the pull request (building with Maven, verify, ...).

Then, you can amend the commit, squash several commits in one, rebase, etc. Basically, it's where you are preparing the merge.

Merging the Pull Request
----------------------------------
Once the pull request branch is ready, you can merge on master:

```
git checkout master
git merge --no-ff -m "[CARBONDATA-140] This closes #63" pr-63
git push
```

Once the merge has been done, you can delete the pull request branch:

```
git branch -D pr-63
```

**Pull request merged**
