### PR TITLE
[CARBONDATA-953] Added validations in Unsafe dataload.

### PR DESCRIPTION
**Pull request by ravipesala**
Added validations to Unsafe dataload, now there are no validations of how much chunksize can be configured and how much working thread memory uses. Now it is configured max siz to 1GB. And also there is no control of adding data to sort threads so it may lead to out of memory.So this PR fixes it.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1682/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1683/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1684/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1689/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
