### PR TITLE
add testcase for no inverted index

### PR DESCRIPTION
**Pull request by Zhangshunyu**
## What changes were proposed in this pull request?

Add test case using multiple rows but discontinuous data results for no inverted index.
CI has passed.

## How was this patch tested?

Pass all the test cases including this new test case.

### CODE REVIEW

**Comment by Zhangshunyu** [comment]
@ravipesala pls check and merge this pr, all test cases and static check has passed.
thank you!

**Comment by Zhangshunyu** [comment]
CI passed:
default

**Comment by ravipesala** [comment]
LGTM

**Comment by Zhangshunyu** [comment]
@chenliang613 pls merge this pr, thank you. Ravindra has reviewed it.

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
