### PR TITLE
[CARBONDATA-498] Refactor compression model for scan

### PR DESCRIPTION
**Pull request by jackylk**
clean up compression model and related code:
1. separate compression model for read and write to reduce the number of object
2. make COMPRESSION_TYPE more understandable
3. move uncompression class to different package according to its functionality

### CODE REVIEW

**Comment by jackylk** [comment]
ok to test

**Comment by CarbonDataQA** [comment]
Build Failed, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/40/

**Comment by CarbonDataQA** [comment]
Build Failed, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/41/

**Comment by CarbonDataQA** [comment]
Build Failed, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/43/

**Comment by CarbonDataQA** [comment]
Build Failed, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/45/

**Comment by CarbonDataQA** [comment]
Build Success, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/46/

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
