### PR TITLE
CARBONDATA-129 Do null check before adding value to CarbonProperties

### PR DESCRIPTION
**Pull request by PraveenAdlakha**

### CODE REVIEW

**Comment by ravipesala** [comment]
LGTM

**Comment by ravipesala** [comment]
@ashokblend Please review this PR

**Comment by ashokblend** [comment]
LGTM

**Comment by PraveenAdlakha** [comment]
@ravipesala  I have rebased it its can be merged now.please do the needful.

**Comment by chenliang613** [comment]
LGTM, thanks for @PraveenAdlakha .

**Pull request closed without merging**
