### PR TITLE
[CARBONDATA-950] Resolved Bug for Class Cast Exception When Selecting Date Type In hive

### PR DESCRIPTION
**Pull request by anubhav100**
This Pr Fixes Bug For Class Cast Exception When Selecting Date Data Type In hive from carbon table
 - Resolved Bug For Class Cast Exception In hive
 - Test It Manually using hive cli

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1761/

**Comment by cenyuhai** [comment]
LGTM.
@chenliang613

**Comment by cenyuhai** [comment]
@QiangCai

**Comment by chenliang613** [comment]
LGTM

**Pull request merged**
